/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { TweetFindManyArgs } from "../../tweet/base/TweetFindManyArgs";
import { Tweet } from "../../tweet/base/Tweet";
import { TweetWhereUniqueInput } from "../../tweet/base/TweetWhereUniqueInput";
import { UserDto } from "../UserDto";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        bio: true,
        createdAt: true,
        email: true,
        id: true,
        password: true,
        profilePic: true,
        updatedAt: true,
        username: true,
        walletAddress: true,
        walletProvider: true,
        walletType: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        bio: true,
        createdAt: true,
        email: true,
        id: true,
        password: true,
        profilePic: true,
        updatedAt: true,
        username: true,
        walletAddress: true,
        walletProvider: true,
        walletType: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        bio: true,
        createdAt: true,
        email: true,
        id: true,
        password: true,
        profilePic: true,
        updatedAt: true,
        username: true,
        walletAddress: true,
        walletProvider: true,
        walletType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          bio: true,
          createdAt: true,
          email: true,
          id: true,
          password: true,
          profilePic: true,
          updatedAt: true,
          username: true,
          walletAddress: true,
          walletProvider: true,
          walletType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          bio: true,
          createdAt: true,
          email: true,
          id: true,
          password: true,
          profilePic: true,
          updatedAt: true,
          username: true,
          walletAddress: true,
          walletProvider: true,
          walletType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tweets")
  @ApiNestedQuery(TweetFindManyArgs)
  async findTweets(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Tweet[]> {
    const query = plainToClass(TweetFindManyArgs, request.query);
    const results = await this.service.findTweets(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        id: true,
        timestamp: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tweets")
  async connectTweets(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TweetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tweets: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tweets")
  async updateTweets(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TweetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tweets: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tweets")
  async disconnectTweets(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TweetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tweets: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/get-users")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetUsers(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.GetUsers(body);
  }

  @common.Get("/users")
  @swagger.ApiOkResponse({
    type: UserDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ListUsers(
    @common.Body()
    body: string
  ): Promise<UserDto[]> {
    return this.service.ListUsers(body);
  }
}
